version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - Maven install
  post_build:
    commands:
      - echo Build completed on `date`     
artifacts:
  files:
    - target/track-demo-spring.jar  
    - buildspec.yml
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes